export * as Init from "./ApiV2/Init"
export * as Games from "./ApiV2/Games"
export * as Leagues from "./ApiV2/Leagues"
export * as AdminLeaguesAdditionalReferences from "./ApiV2/Admin/Leagues/AdditionalReference"
export * as GameOperations from "./ApiV2/GameOperations/League"
export * as GamesGame from "./ApiV2/Games/Game"
export * as LeaguesGameDays from "./ApiV2/Leagues/GameDays/GameDay"
export * as LeaguesTable from "./ApiV2/Leagues/Table"
export * as LeaguesGroupedTable from "./ApiV2/Leagues/GroupedTable"
export * as LeaguesSchedule from "./ApiV2/Leagues/Schedule"
export * as LeaguesScorers from "./ApiV2/Leagues/Scorers"
export * as LeaguesLeague from "./ApiV2/Leagues/League"
export * as UserLeaguesPenalties from "./ApiV2/User/Leagues/Penalty"
export * as UserLeaguesPenaltyCodes from "./ApiV2/User/Leagues/PenaltyCode"

